import {STEPS,TEMPLATES,FABRICS,COLORS,clamp,distance,seed,newProject,setTemplate,samplePath,transform,invalidate,canNext,goNext,goBack,snapshot,navigateTo,stepBlockedReason} from './engine.mjs';
import {StageRenderer,drawThumbnail,makeSwatch} from './render.mjs';
import {inspectImageHeader,extractContour} from './image-engine.mjs';
const $=q=>document.querySelector(q),state=newProject(),renderer=new StageRenderer($('#stage'));
const labels=['开始','图案','修线','针距','走针','抽紧','配色','浸染','展开','完成'];
let raf=0,toastTimer=0,stroke=null,drag=null,dyeStart=0,dyeElapsed=0,lastTime=0,reveal=0,replay=false,exporting=false,localImage=null,dyeFinished=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function modal(html){$('#dialog-content').innerHTML=html;$('#dialog').showModal();}
$('#close-dialog').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))$('#dialog').close();});
$('#help').onclick=()=>modal('<p class="eyebrow">关于这次体验</p><h2>让图案，慢慢染出来。</h2><p>选择图案，沿轮廓走针，拉紧线头，再把布放入染缸。线扎住的部分留下浅色，周围自然渗开。</p><p>这是独立网页交互预览。图片和制作过程只在当前设备中处理，关页后草稿不保留。成品可下载 PNG；小红书内保存、笔记发布和作品链接暂未接入。</p><p>当前效果是工艺启发的视觉模拟，不能预测真实材料的染色结果。</p>');
$('#reset').onclick=()=>modal('<h2>重新铺一块布？</h2><p>当前未下载的作品和制作进度会清空。</p><div class="dialog-actions"><button class="secondary" id="keep">继续制作</button><button class="primary" id="confirm-reset">重新开始</button></div>');
$('#dialog').addEventListener('click',e=>{if(e.target.id==='keep')$('#dialog').close();if(e.target.id==='confirm-reset'){Object.assign(state,newProject());localImage=null;replay=false;reveal=0;dyeElapsed=0;$('#dialog').close();render();}});
const heading=(num,title,description)=>`<p class="eyebrow">${num} / 一针一染</p><h2>${title}</h2><p class="description">${description}</p>`;
const slider=(id,title,value,min,max,step,display,left,right)=>`<div class="slider-row"><label class="slider-head" for="${id}">${title}<output id="${id}-value">${display}</output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><div class="range-hints"><span>${left}</span><span>${right}</span></div></div>`;
const pct=v=>Math.round(v*100)+'%';
function panel(){switch(state.step){
case 'intro':return `<p class="eyebrow">一块布，一点蓝，一点你的想象</p><h1>把喜欢的图案，<br>一针一线染出来。</h1><p class="intro-copy">沿着轮廓慢慢走，拉紧线头，<br>再等一抹颜色在布上散开。<br>你的第一件扎染，就从这里开始。</p><div class="intro-detail"><span><b>5 个</b>小小图案</span><span><b>3 分钟</b>慢慢动手</span><span><b>独一份</b>手作色晕</span></div>`;
case 'pattern':return heading('01','选一个，染进布里。','先从简单的轮廓开始。你的手作，不必复杂。')+`<div class="template-grid">${TEMPLATES.map(t=>`<button class="template-button ${state.patternId===t.id?'selected':''}" data-template="${t.id}" aria-pressed="${state.patternId===t.id}"><canvas width="90" height="90" data-thumb="${t.id}" aria-hidden="true"></canvas>${t.name}</button>`).join('')}</div><button class="upload-button" id="upload">＋ 从设备选择线稿</button><input id="file" type="file" accept="image/png,image/jpeg" hidden><p class="upload-note">白底黑线或实心剪影更合适。图片仅在本机处理。</p>`;
case 'contour':return heading('02','把轮廓，放得刚刚好。','调整大小和方向，让线条在布面上舒展开。')+slider('scale','图案大小',state.scale,.65,1.15,.01,pct(state.scale),'小一点，留白更多','大一点，轮廓更醒目')+slider('rotation','旋转',state.rotation*180/Math.PI,-45,45,1,Math.round(state.rotation*180/Math.PI)+'°','向左','向右')+`<div class="tool-row"><button id="simplify">简化线条</button><button id="undo-contour">撤销调整</button><button id="restore-contour">恢复原样</button></div><p class="info-note">修改轮廓后需要重新走针。此版支持大小、方向与简化；局部擦除和连接断线将在后续加入。</p>`;
case 'spacing':return heading('03','针脚细密，还是粗犷？','细针脚勾出清楚的边，疏一点则多些随性的色晕。')+slider('spacing','针距',state.spacing,3,9,.5,state.spacing+' mm','细密 · 轮廓精准','粗犷 · 手作感更强')+`<div class="hint-box">这条轮廓约有 <strong id="stitch-count">${samplePath(state.points,state.spacing).length}</strong> 个落针点。布面的点会跟着针距一起变化。</div><p class="info-note">调整针距会清空走针，需要重新缝线。毫米对应虚拟布面，不作为实际制作尺寸。</p>`;
case 'stitching':return heading('04','沿着线，慢慢走。','从金色圆圈附近开始，按住画布沿轮廓滑动。松手后可以接着缝。')+`<div class="big-number" id="sewn-percent">${Math.round(state.stitched.length/samplePath(state.points,state.spacing).length*100)}<small>%</small></div><div class="progress-track"><span id="sewn-bar" style="width:${state.stitched.length/samplePath(state.points,state.spacing).length*100}%"></span></div><div class="progress-caption"><span>每一针都算数</span><span id="sewn-count">${state.stitched.length} / ${samplePath(state.points,state.spacing).length}</span></div><div class="tool-row"><button id="undo-stroke">撤回上一段</button><button id="auto-stitch">帮我缝完余下的线</button></div><p class="info-note">偏一点也没关系。金色线段是已经完成的针脚；辅助完成也能继续体验。</p>`;
case 'gathering':return heading('05','轻轻一拉，布就起了褶。',state.immersion>=.5?'拖动滑杆，直接比较松紧对成品留白和渗色的影响。':'按住画布右侧的线头，向右拉。松手后，布料会记住这个松紧。')+slider('tension','抽紧程度',state.tension,0,1,.01,pct(state.tension),'松一点 · 色晕柔和','紧一点 · 留白清楚')+`<p class="info-note">也可以拖动上面的滑杆调节。这里不会断线，慢一点就好。</p>`;
case 'material':return heading('06','一块布，一种心情。','换一种织纹，再挑一个今天喜欢的颜色。')+`<div class="fabric-list">${FABRICS.map(f=>`<button class="fabric-button ${state.fabricId===f.id?'selected':''}" data-fabric="${f.id}" aria-pressed="${state.fabricId===f.id}"><canvas width="70" height="45" data-fabric-canvas="${f.id}" aria-hidden="true"></canvas>${f.name}</button>`).join('')}</div><p class="fabric-description" id="fabric-description">${FABRICS.find(f=>f.id===state.fabricId).description}</p><div class="section-label"><span>染料颜色</span><span class="color-label">${COLORS.find(c=>c.hex===state.color)?.name??'自选色'}</span></div><div class="color-list">${COLORS.map(c=>`<button class="color-button ${state.color===c.hex?'selected':''}" style="background:${c.hex}" data-color="${c.hex}" aria-label="${c.name}" aria-pressed="${state.color===c.hex}"></button>`).join('')}</div>`+slider('concentration','染料浓度',state.concentration,0,4,1,['清浅','轻染','标准','浓郁','深染'][[.1,.3,.5,.75,1].indexOf(state.concentration)],'清浅 · 轻轻着色','深染 · 颜色浓郁');
case 'dyeing':return heading('07','让颜色，慢慢进去。','浸得越久，颜色越深。到了合适的时候，就可以提起布料。')+`<div class="big-number"><span id="dye-seconds">${Math.floor(state.immersion*10)}</span><small>/ 10 秒</small></div><div class="progress-track"><span id="dye-bar" style="width:${pct(state.immersion)}"></span></div><div class="dye-stages"><span data-dye-stage="0">刚入染</span><span data-dye-stage="1">开始吸色</span><span data-dye-stage="2">已经成色</span><span data-dye-stage="3">深度浸染</span></div><label class="hint-box" style="display:block"><input type="checkbox" id="auto-lift" checked> 在推荐的 7 秒时自动提起</label>`;
case 'reveal':return heading('08','拆开线，见到你的颜色。','把布轻轻铺开，藏在线里的图案正在显现。')+`<div class="big-number" id="reveal-caption">${replay?'再看一遍':'拆线中'}</div><p class="info-note">不需要每次都等待。你可以直接展开，看看属于这一次的色晕。</p>`;
case 'result':return `<span class="result-tag">一件小小的手作，完成了</span><h2>${esc(state.name)}，染好了。</h2><p class="description">有些边缘整齐，有些颜色悄悄走远。<br>这些不完全一样的地方，刚好属于你。</p><div class="result-params"><div><span>布料</span><strong>${FABRICS.find(f=>f.id===state.fabricId).name}</strong></div><div><span>染料</span><strong>${COLORS.find(c=>c.hex===state.color)?.name??'自选色'}</strong></div><div><span>针距 / 松紧</span><strong>${state.spacing} mm / ${pct(state.tension)}</strong></div><div><span>浸染</span><strong>${(state.immersion*10).toFixed(1)} 秒</strong></div></div><div class="result-tools"><button class="soft-button" id="recolor">同图换个颜色</button><button class="soft-button" id="redye">再染一次</button></div><button class="knowledge-link" id="knowledge">为什么线走过的地方，会留下白色？</button><p class="save-note">下载为 PNG 图片。网页预览暂不提供小红书发布或单件作品链接。</p>`;
}}
let contourHistory=[],navigationKey='';
function recordContour(){contourHistory.push({points:structuredClone(state.points),basePoints:structuredClone(state.basePoints),scale:state.scale,rotation:state.rotation});if(contourHistory.length>20)contourHistory.shift();}
function renderSteps(){const current=STEPS.indexOf(state.step);$('#steps').innerHTML=STEPS.slice(1).map((step,j)=>{const blocked=stepBlockedReason(state,step);return `<button type="button" data-step="${step}" class="step ${current===j+1?'current':!blocked?'done':''}" aria-label="${String(j+1).padStart(2,'0')} ${labels[j+1]}" aria-disabled="${!!blocked}" ${current===j+1?'aria-current="step"':''} title="${blocked||'点击调整'+labels[j+1]}"><span class="step-num">${String(j+1).padStart(2,'0')}</span>${labels[j+1]}</button>`;}).join('');}
function jump(step){const reason=stepBlockedReason(state,step);if(reason){toast(reason);return;}if(state.step===step)return;stroke=null;drag=null;navigateTo(state,step);if(step==='dyeing'&&dyeFinished){state.immersion=0;dyeFinished=false;}dyeElapsed=state.immersion*10000;replay=state.immersion>=.5;reveal=0;render();}
$('#steps').onclick=e=>{const b=e.target.closest('[data-step]');if(b)jump(b.dataset.step);};
function render(){if(state.immersion===0)dyeFinished=false;if(['reveal','result'].includes(state.step))dyeFinished=true;document.body.dataset.step=state.step;cancelAnimationFrame(raf);lastTime=0;const i=STEPS.indexOf(state.step);renderSteps();$('#panel').innerHTML=panel();$('#back').hidden=i===0;$('#reset').hidden=i===0;$('#thread-handle').hidden=state.step!=='gathering'||state.immersion>=.5;$('#stage-label').textContent=`${String(Math.max(1,i)).padStart(2,'0')} / ${['灵感落在布上','选一幅小小图案','留出舒展的空间','一针一线，都看得见','沿着轮廓，把线留下','布里的褶，开始聚拢','把喜欢的颜色染进去','颜色正在慢慢散开','把惊喜轻轻展开','这一次，只属于你'][i]}`;$('#stage-meta').textContent=`${FABRICS.find(f=>f.id===state.fabricId).name} · 200 × 200`;
 $('#canvas-hint').textContent=state.immersion>=.5&&['gathering','material'].includes(state.step)?'正在预览调整后的成品 · 点击「完成」查看与下载':state.step==='stitching'?'按住沿线滑动 · 松手可以续缝':state.step==='gathering'?'拖动右侧线头，或用滑杆调节松紧':state.step==='result'?'色晕和留白，都留在这一块布上。':'每一次渗色，都留一点意外。';
 $('#next').innerHTML=state.step==='result'?'下载作品 PNG <span aria-hidden="true">↓</span>':state.step==='intro'?'开始制作 <span aria-hidden="true">→</span>':state.step==='material'?(state.immersion>=.5?'查看调整后的作品 <span aria-hidden="true">→</span>':'放入染缸 <span aria-hidden="true">→</span>'):state.step==='dyeing'?'提起布料':state.step==='reveal'?'直接展开':'下一步 <span aria-hidden="true">→</span>';
 $('#step-note').textContent=state.step==='intro'?'不用准备材料，也不用担心失败。':state.step==='dyeing'?'至少浸染 5 秒，才能提起。离开后可回来继续。':state.step==='result'?'可点击顶部步骤调整；点击「浸染」会重新计时。作品未自动公开。':'';updateNext();
 document.querySelectorAll('[data-thumb]').forEach(c=>drawThumbnail(c,TEMPLATES.find(t=>t.id===c.dataset.thumb).points));document.querySelectorAll('[data-fabric-canvas]').forEach(c=>makeSwatch(c,c.dataset.fabricCanvas));
 if(state.step==='material')$('#concentration').value=[.1,.3,.5,.75,1].indexOf(state.concentration);
 bindPanel();draw();if(['dyeing','reveal'].includes(state.step))raf=requestAnimationFrame(tick);
}
function draw(){renderer.draw(state,{reveal,time:performance.now()});}
function updateNext(){const key=STEPS.slice(1).map(v=>!!stepBlockedReason(state,v)).join();if(key!==navigationKey){navigationKey=key;renderSteps();}$('#next').disabled=state.step==='result'?exporting:state.step==='reveal'?false:!canNext(state);}
function bindPanel(){
 document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{setTemplate(state,b.dataset.template);contourHistory=[];render();});
 document.querySelectorAll('[data-fabric]').forEach(b=>b.onclick=()=>{state.fabricId=b.dataset.fabric;invalidate(state,'material');render();});
 document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{state.color=b.dataset.color;invalidate(state,'material');render();});
 for(const id of ['scale','rotation','spacing','tension','concentration']){const el=$('#'+id);if(!el)continue;el.addEventListener('pointerdown',()=>{if(['scale','rotation'].includes(id))recordContour();});el.addEventListener('keydown',()=>{if(['scale','rotation'].includes(id))recordContour();});el.oninput=()=>{const v=Number(el.value);if(id==='scale'||id==='rotation'){state[id]=id==='rotation'?v*Math.PI/180:v;state.points=transform(state.basePoints,state.scale,state.rotation);invalidate(state,'contour');$('#'+id+'-value').textContent=id==='scale'?pct(v):v+'°';}else if(id==='spacing'){state.spacing=v;invalidate(state,'spacing');$('#spacing-value').textContent=v+' mm';$('#stitch-count').textContent=samplePath(state.points,v).length;}else if(id==='tension'){state.tension=v;invalidate(state,'gathering');$('#tension-value').textContent=pct(v);}else {state.concentration=[.1,.3,.5,.75,1][v];invalidate(state,'material');$('#concentration-value').textContent=['清浅','轻染','标准','浓郁','深染'][v];}draw();updateNext();};}
 if($('#restore-contour'))$('#restore-contour').onclick=()=>{recordContour();state.scale=1;state.rotation=0;state.points=structuredClone(state.basePoints);invalidate(state,'contour');render();};
 if($('#simplify'))$('#simplify').onclick=()=>{recordContour();if(state.basePoints.length>24){state.basePoints=state.basePoints.filter((_,i)=>i%2===0);state.points=transform(state.basePoints,state.scale,state.rotation);invalidate(state,'contour');render();toast('细小线条已简化，可撤销。');}else toast('轮廓已经足够简洁。');};
 if($('#undo-contour'))$('#undo-contour').onclick=()=>{const old=contourHistory.pop();if(old){Object.assign(state,old);invalidate(state,'contour');render();}else toast('还没有可以撤销的调整。');};
 if($('#auto-stitch'))$('#auto-stitch').onclick=()=>{state.strokeHistory.push([...state.stitched]);state.stitched=samplePath(state.points,state.spacing).map((_,i)=>i);invalidate(state,'stitching');render();toast('余下的针脚已经缝好。');};
 if($('#undo-stroke'))$('#undo-stroke').onclick=()=>{const prev=state.strokeHistory.pop();if(prev){state.stitched=prev;invalidate(state,'stitching');render();}else toast('还没有可以撤回的走线。');};
 if($('#redye'))$('#redye').onclick=()=>{state.randomSeed=seed();state.immersion=0;state.step='dyeing';dyeElapsed=0;render();};
 if($('#recolor'))$('#recolor').onclick=()=>jump('material');
 if($('#knowledge'))$('#knowledge').onclick=()=>modal('<p class="eyebrow">一张工艺小卡</p><h2>线扎住的地方，<br>把颜色挡在外面。</h2><p>缝线抽紧后，布料挤在一起，染液不容易进入紧密折叠的部分。展开时，那些地方便比周围更浅。松紧、织纹和浸染过程都会影响色晕，所以手工扎染很难有两件完全一样的作品。</p><p>当前画布是对这种防染关系的视觉演示，不是实际工艺的物理预测。</p><p>工艺背景：<a href="https://www.ihchina.cn/project_details/14304.html" target="_blank" rel="noopener noreferrer">中国非物质文化遗产网 · 白族扎染技艺</a></p>');
 if($('#upload'))$('#upload').onclick=()=>$('#file').click();if($('#file'))$('#file').onchange=e=>handleUpload(e.target.files[0]);
}
$('#next').onclick=async()=>{if(state.step==='result'){await exportImage();return;}if(state.step==='material'&&state.immersion>=.5){jump('result');return;}if(state.step==='reveal'){reveal=1;state.step='result';render();return;}if(goNext(state)){if(state.step==='dyeing'){dyeElapsed=state.immersion*10000;}if(state.step==='reveal'){reveal=0;replay=false;}render();}};
$('#back').onclick=()=>{if(state.step==='result'){state.step='reveal';reveal=0;replay=true;render();return;}goBack(state);dyeElapsed=state.immersion*10000;render();};
function tick(time){const dt=lastTime?Math.min(time-lastTime,100):0;lastTime=time;if(!document.hidden){if(state.step==='dyeing'){dyeElapsed+=dt;state.immersion=clamp(dyeElapsed/10000);$('#dye-seconds').textContent=(state.immersion*10).toFixed(1);$('#dye-bar').style.width=pct(state.immersion);const phase=state.immersion<.2?0:state.immersion<.5?1:state.immersion<.85?2:3;document.querySelectorAll('[data-dye-stage]').forEach(e=>e.classList.toggle('active',Number(e.dataset.dyeStage)<=phase));updateNext();if(state.immersion>=.7&&$('#auto-lift').checked){state.step='reveal';reveal=0;render();return;}}else if(state.step==='reveal'){reveal=clamp(reveal+dt/2600);$('#reveal-caption').textContent=reveal<.22?'线松开了':reveal<.8?'慢慢展开':'染好了';if(reveal>=1){state.step='result';render();return;}}draw();}if(['dyeing','reveal'].includes(state.step))raf=requestAnimationFrame(tick);}
document.addEventListener('visibilitychange',()=>{lastTime=0;stroke=null;drag=null;});
const stage=$('#stage');stage.onpointerdown=e=>{if(state.step!=='stitching')return;stage.setPointerCapture(e.pointerId);stroke={id:e.pointerId,previous:[...state.stitched],last:null};sew(e);};stage.onpointermove=e=>{if(stroke?.id===e.pointerId)sew(e);};
function sew(e){const p=renderer.pointFromEvent(e),points=samplePath(state.points,state.spacing);let nearest=-1,min=.045;points.forEach((q,i)=>{const d=distance(p,q);if(d<min){min=d;nearest=i;}});if(nearest<0)return;const set=new Set(state.stitched);set.add(nearest);if(stroke.last!==null){const n=points.length,diff=nearest-stroke.last,short=diff>n/2?diff-n:diff<-n/2?diff+n:diff;if(Math.abs(short)<=6){for(let j=0;j<=Math.abs(short);j++)set.add((stroke.last+j*Math.sign(short)+n)%n);}}stroke.last=nearest;state.stitched=[...set].sort((a,b)=>a-b);const ratio=state.stitched.length/points.length;$('#sewn-percent').innerHTML=Math.round(ratio*100)+'<small>%</small>';$('#sewn-bar').style.width=pct(ratio);$('#sewn-count').textContent=`${state.stitched.length} / ${points.length}`;draw();updateNext();}
function endStroke(e){if(stroke&&stroke.id===e.pointerId){if(state.stitched.length!==stroke.previous.length){state.strokeHistory.push(stroke.previous);if(state.strokeHistory.length>20)state.strokeHistory.shift();invalidate(state,'stitching');}stroke=null;}}stage.onpointerup=endStroke;stage.onpointercancel=endStroke;
const handle=$('#thread-handle');handle.onpointerdown=e=>{handle.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,time:performance.now(),initial:state.tension,lastX:e.clientX,lastTime:performance.now()};};handle.onpointermove=e=>{if(drag?.id!==e.pointerId)return;const now=performance.now(),w=stage.getBoundingClientRect().width,travel=(e.clientX-drag.x)/(w*.3),velocity=Math.abs(e.clientX-drag.lastX)/Math.max(now-drag.lastTime,1),steady=clamp((now-drag.time)/1600),speedScore=1-clamp(Math.abs(velocity-.25)/1.5);state.tension=clamp(drag.initial+travel*.6+steady*.08+Math.abs(travel)*speedScore*.15);state.stability=steady;state.speed=clamp(velocity/2);drag.lastX=e.clientX;drag.lastTime=now;invalidate(state,'gathering');$('#tension').value=state.tension;$('#tension-value').textContent=pct(state.tension);draw();};handle.onpointerup=handle.onpointercancel=()=>{drag=null;};
async function exportImage(){if(exporting)return;exporting=true;updateNext();try{const out=document.createElement('canvas');out.width=1400;out.height=1600;const ctx=out.getContext('2d');ctx.fillStyle='#f5f2e9';ctx.fillRect(0,0,out.width,out.height);ctx.drawImage(renderer.dye(state),70,70,1260,1260);ctx.fillStyle='#203b70';ctx.font='42px sans-serif';ctx.fillText('扎染 DIY · '+state.name,75,1420);ctx.font='24px sans-serif';ctx.fillStyle='#758095';ctx.fillText(`${FABRICS.find(f=>f.id===state.fabricId).name} / 针距 ${state.spacing} mm / ${(state.immersion*10).toFixed(1)} 秒浸染`,75,1475);const blob=await new Promise((resolve,reject)=>out.toBlob(b=>b?resolve(b):reject(new Error('导出为空')),'image/png'));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`扎染-${state.name}-${state.randomSeed}.png`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('已开始下载。手机浏览器可在下载列表中查看。');}catch{toast('这次图片没有导出成功，请再试一次。');}finally{exporting=false;updateNext();}}
async function handleUpload(file){if(!file)return;const revision=state.revision;const button=$('#upload');button.disabled=true;button.textContent='正在本机寻找轮廓…';try{
 if(file.size>10_000_000)throw new Error('请先把图片缩小到 10 MB 以内。');const buffer=await file.arrayBuffer(),header=inspectImageHeader(buffer);if(!header.width||!header.height||header.width>12000||header.height>12000||header.width*header.height>24_000_000)throw new Error('图片尺寸太大，请先缩小后再选择。');
 const bitmap=await createImageBitmap(new Blob([buffer],{type:header.type}),{imageOrientation:'from-image'});const c=document.createElement('canvas');const scale=Math.min(1,1024/Math.max(bitmap.width,bitmap.height));c.width=Math.max(1,Math.round(bitmap.width*scale));c.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();
 const small=document.createElement('canvas');const ratio=160/Math.max(c.width,c.height);small.width=Math.max(3,Math.round(c.width*ratio));small.height=Math.max(3,Math.round(c.height*ratio));const sc=small.getContext('2d');sc.drawImage(c,0,0,small.width,small.height);const pixels=sc.getImageData(0,0,small.width,small.height).data,gray=new Uint8Array(small.width*small.height);for(let i=0;i<gray.length;i++)gray[i]=.2126*pixels[i*4]+.7152*pixels[i*4+1]+.0722*pixels[i*4+2];const result=extractContour(gray,small.width,small.height);
 if(state.revision!==revision||state.step!=='pattern')return;localImage=c;Object.assign(state,{patternId:'upload',name:'我的线稿',points:result.points,basePoints:structuredClone(result.points),scale:1,rotation:0});invalidate(state,'pattern');contourHistory=[];state.step='contour';render();toast(result.warning);
 }catch(error){if(state.revision===revision&&state.step==='pattern')toast(error.message||'没有识别到合适轮廓，请换图或选模板。');}finally{if($('#upload')){$('#upload').disabled=false;$('#upload').textContent='＋ 从设备选择线稿';}}}
render();
